name: Test-Snakemake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install snakefmt
        run: |
          pip install snakefmt

      - name: Formatting
        run: |
          cd snakemake
          snakefmt --check workflow/Snakefile workflow/rules/*.smk

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.20.0
      with:
        stagein: cd snakemake
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v2

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.20.0
      with:
        stagein: cd snakemake
        directory: .
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"